name = "OdeMMHPlanner"
uuid = "aa6e6aa3-39df-4343-855d-9df50e730bdb"
version = "0.1.0"
authors = ["Robert Lefringhausen <robert.lefringhausen@tum.de>"]

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
DifferentialEquations = "7"
Distributions = "0.25"
ForwardDiff = "1"
Ipopt = "1"
JLD2 = "0.6"
JuMP = "1"
LinearAlgebra = "1"
Plots = "1"
Random = "1"
Statistics = "1"
StatsBase = "0.34"
StatsPlots = "0.15"
julia = "1.12"

[workspace]
projects = ["docs"]